# Generated by Django 3.2.9 on 2021-11-14 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_receipt_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
