# Generated by Django 3.2.9 on 2021-11-14 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='receipt',
            field=models.ForeignKey(default='None', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.receipt'),
        ),
    ]
